stages:
  - build
  - test
  - docker
  - deploy

build:
  stage: build
  image: maven:3.9.6-eclipse-temurin-21
  script: 
    - mvn clean package -DskipTests
  artifacts:
    paths: 
      - target/*.jar

test:
  stage: test
  image: maven:3.9.6-eclipse-temurin-21
  script:
    - mvn test

docker:
  stage: docker
  image: docker:26
  services:
    - docker:26-dind
  variables:
    DOCKER_TLS_CERTDIR: ""
  script: 
    - docker build -t agroshop/myawsrepository .
    - aws ecr get-login-password --region us-east-2 |
      docker login --username AWS --password-stdin 343218178986.dkr.ecr.us-east-2.amazonaws.com
    - docker tag agroshop:latest 343218178986.dkr.ecr.us-east-2.amazonaws.com/agroshop/myawsrepository:latest
    - docker push 343218178986.dkr.ecr.us-east-2.amazonaws.com/agroshop/myawsrepository:latest

deploy:
  stage: deploy
  image: amazon/aws-cli:2
  script: 
    - aws ecs update-service --cluster fantastic-squirrel-hf46vn --service default-myawsrepository-a91a-service-wpgouwwy --force-new-deployment