spring.application.name=agroshop
server.port=8080

spring.config.import=optional:file:.env[.properties]

app.frontend.url=http://localhost:5174

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

api.prefix=/api/v1

api.useSecureCookie=false

auth.token.accessExpirationInMils=900000

auth.token.refreshExpirationInMils=604800000

auth.token.jwtSecret=${AUTH_TOKEN_JWTSECRET}

cors.allowed.origins=http://localhost:5174,http://localhost:5173

# google oauth2
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile

spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
spring.security.oauth2.client.provider.google.user-name-attribute=email

app.oauth2.redirect-url=http://localhost:5174/oauth2/redirect

# melhor envio 
melhorenvio.client-id=${MELHORENVIO_CLIENT_ID}
melhorenvio.client-secret=${MELHORENVIO_CLIENT_SECRET}
melhorenvio.redirect-uri=http://localhost:8080/melhorenvio/oauth/callback
melhorenvio.base-url=https://sandbox.melhorenvio.com.br

melhorenvio.token=${MELHORENVIO_TOKEN}

cep-origem=94935050

#mercado pago
mercadopago.public-key=${MERCADOPAGO_PUBLIC_KEY}
mercadopago.access-token=${MERCADOPAGO_ACCESS_TOKEN}
# mercadopago.notification-url=http://localhost:8080/api/v1/mercadopago/notification